<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <RootNamespace>ParcelBuilder</RootNamespace>
    <AssemblyName>ParcelBuilder.Core</AssemblyName>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>

</Project>
